# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8dac6a6d3f5fcc1e65543f79085bc1041889ce420996dd7a8f5f65b9df8bc5741710750b2ee93f0eb1b5af9f2b24cf20a50452c069f8ae9a954439de960d5b80

test:
  secret_key_base: 4ae27f07babb0f9a8c43f7cb09f64494cfd98894baa334e1015d05f5d4ac3915a967aeb3c3dafdde55451c47df6988cd6ed468a95b190eda570827482175599e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
